server:
  port: 8081

spring:
  application:
    name: eventapp
  config:
    import: configserver:http://localhost:9296

  datasource:
    url: jdbc:mysql://localhost:3306/eventapp
    username: root
    password: Iceburg2103$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true       # Logs SQL queries to the console
    properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
