server:
  port: 8082

spring:
  application:
    name: attendeemgmt
  config:
    import: configserver:http://localhost:9296
#  eureka:
#    client:
#      defaultZone: localhost
#      register-with-eureka: true
#      fetch-registry: true
#    instance:
#      prefer-ip-address: true

  datasource:
    url: jdbc:mysql://localhost:3306/attendeemgmt
    username: root
    password: Iceburg2103$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true       # Logs SQL queries to the console
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect





